### PR TITLE
Fix DataModel crash after deserialization

### LINKED ISSUE #248: DataModel.updateListeners can crash after deserialization

### PR DESCRIPTION
**Pull request by thusson13**
Fixes https://github.com/wayfair/brickkit-android/issues/248

### CODE REVIEW

**Review by dgoldhirsch4 — APPROVED** [review]
LGTM

File: BrickKit/bricks/src/main/java/com/wayfair/brickkit/brick/DataModel.kt [hunk 1]
```diff
@@ -11,15 +11,21 @@ import java.io.Serializable
...
+        }
 
     /**
      * Add a [DataModelUpdateListener] to the list of listeners.
      *
      * @param updateListener the listener to add
      */
     open fun addUpdateListener(updateListener: DataModelUpdateListener) {
-        updateListeners.add(updateListener)
+        updateListeners!!.add(updateListener)
```
Comment (kenyee) [inline BrickKit/bricks/src/main/java/com/wayfair/brickkit/brick/DataModel.kt:28]: could also just use ?.add but that'd hide the bug... :-)

**Review by kenyee — APPROVED** [review]

File: BrickKit/bricks/src/main/java/com/wayfair/brickkit/brick/DataModel.kt (hunk 1 above)
Comment (thusson13) [reply BrickKit/bricks/src/main/java/com/wayfair/brickkit/brick/DataModel.kt:28]: yeah I tried a bunch of different combos of stuff and its really just gross
